
local reanimatorSpawnSet = {
	name = "death_penalty",
	prettyName = "Death Penalty",
	description = "For masochists and sadists",
	difficultyPerMin = "default*2",
	waveInterval = "default",
	diffBumpWhenWaveKilled = "default",
	startingBudget = { 2, 6 },
	spawnCountPerDifficulty = 1,
	startingSpawnCount = 15,
	maxSpawnCount = 30,
	maxSpawnDist = "default",
	roundEndSound = "music/ravenholm_1.mp3",
	roundStartSound = "npc/fast_zombie/fz_alert_far1.wav",
	spawns = {
		{
			hardRandomChance = 8,
			name = "zambie_reanimator",
			prettyName = "Reanimator Zombie",
			class = "terminator_nextbot_zambiereanimator",
			spawnType = "hunter",
			difficultyCost = { 20, 25 },
			countClass = "terminator_nexbot_zambiereanimator",
			maxCount = { 2, 3 },	
		},
		{
			hardRandomChance = 1,
			name = "zambie_reanimator_elite",
			prettyName = "The Menace",
			class = "terminator_nextbot_zambiereanimatorelite",
			spawnType = "hunter",
			difficultyCost = { 200, 250 },
			countClass = "terminator_nexbot_zambiereanimatorelite",
			maxCount = 1,			
		},
		{
			hardRandomChance = 40,
			name = "zambie_flame",
			prettyName = "Flaming Zombie",
			class = "terminator_nextbot_zambieflame",
			spawnType = "hunter",
			difficultyCost = { 3 },
			countClass = "terminator_nextbot_zambieflame*",
			maxCount = { 8, 12 },			
		},
		{
			hardRandomChance = { 8, 10 },
			name = "zambie_flame_fast",
			prettyName = "Flaming Zombie Fast",
			class = "terminator_nextbot_zambieflamefast",
			spawnType = "hunter",
			difficultyCost = { 5, 8 },
			countClass = "terminator_nextbot_zambieflame*",
			maxCount = 4,			
		},
		{
			hardRandomChance = 40,
			name = "zambie_acid",
			prettyName = "Acid Zombie",
			class = "terminator_nextbot_zambieacid",
			spawnType = "hunter",
			difficultyCost = { 3 },
			countClass = "terminator_nextbot_zambieacid*",
			maxCount = { 8, 12 },			
		},
		{
			hardRandomChance = { 8, 10 },
			name = "zambie_acid_fast",
			prettyName = "Acid Zombie Fast",
			class = "terminator_nextbot_zambieacidfast",
			spawnType = "hunter",
			difficultyCost = { 5, 8 },
			countClass = "terminator_nextbot_zambieacid*",
			maxCount = 4,			
		},
		{
			hardRandomChance = 25,
			name = "zambie_energy",
			prettyName = "Energy Zombie",
			class = "terminator_nextbot_zambieenergy",
			spawnType = "hunter",
			difficultyCost = { 6 },
			countClass = "terminator_nextbot_zambieenergy*",
			maxCount = { 6, 9 },			
		},
		{
			hardRandomChance = { 6, 8 },
			name = "zambie_energy_fast",
			prettyName = "Energy Zombie Fast",
			class = "terminator_nextbot_zambieenergyfast",
			spawnType = "hunter",
			difficultyCost = { 8, 10 },
			countClass = "terminator_nextbot_zambieenergy*",
			maxCount = 3,			
		},
		{
			hardRandomChance = { 8, 12 },
			name = "zambie_glass_elite",
			prettyName = "Glass Zombie Elite",
			class = "terminator_nextbot_zambieglasselite",
			spawnType = "hunter",
			difficultyCost = { 25, 35 },
			countClass = "terminator_nextbot_zambieglasselite",
			maxCount = { 2, 4 },			
		},
		{
			hardRandomChance = { 0, 1 },
			name = "zambie_glass_titan",
			prettyName = "Glass Zombie Titan",
			class = "terminator_nextbot_zambieglasstitan",
			spawnType = "hunter",
			difficultyCost = { 250, 300 },
			difficultyRequired = { 2750, 3500 },
			countClass = "terminator_nextbot_zambieglasstitan",
			maxCount = { 1, 2 },			
		},
		{
			hardRandomChance = { 0, 3 },
			name = "zambie_mech",
			prettyName = "Mecha Zombie",
			class = "terminator_nextbot_zambiemecha",
			spawnType = "hunter",
			difficultyCost = { 175, 225 },
			countClass = "terminator_nextbot_zambiemecha",
			maxCount = { 2, 3 },
		},
		{
			hardRandomChance = { 0, 1 },
			name = "zambie_mech_elite",
			prettyName = "Mecha Zombie Elite",
			class = "terminator_nextbot_zambiemechaelite",
			spawnType = "hunter",
			difficultyCost = { 275, 300 },
			difficultyRequired = { 3000, 4000 },
			countClass = "terminator_nextbot_zambiemecha*",
			maxCount = { 1 },
		},
	}

}

table.insert( GLEE_SPAWNSETS, reanimatorSpawnSet )
