
local reanimatorSpawnSet = {
	name = "gleesyphus",
	prettyName = "Gleesyphus",
	description = "One must imagine Sisyphus gleeful...",
	difficultyPerMin = "default",
	waveInterval = "default",
	diffBumpWhenWaveKilled = "default",
	startingBudget = "default",
	spawnCountPerDifficulty = "default",
	startingSpawnCount = { 6, 8 },
	maxSpawnCount = 12,
	roundEndSound = "music/ravenholm_1.mp3",
	roundStartSound = "ambient/creatures/town_zombie_call1.wav",
	chanceToBeVotable = 10,
	spawns = {
		{
			hardRandomChance = { 15, 25 },
			name = "zambie_reanimator",
			prettyName = "Reanimator Zombie",
			class = "terminator_nextbot_zambiereanimator",
			spawnType = "hunter",
			difficultyCost = { 75, 90 },
			countClass = "terminator_nexbot_zambiereanimator",
			maxCount = { 2, 3 },	
		},
		{
			hardRandomChance = { 0.5, 2 },
			name = "zambie_reanimator_early",
			prettyName = "Reanimator Zombie Rare",
			class = "terminator_nextbot_zambiereanimator",
			spawnType = "hunter",
			difficultyCost = { 6, 8 },
			difficultyStopAfter = { 200, 250 },
			countClass = "terminator_nexbot_zambiereanimator",
			maxCount = { 1 },	
		},
		{
			hardRandomChance = 1,
			name = "zambie_reanimator_elite",
			prettyName = "The Menace",
			class = "terminator_nextbot_zambiereanimatorelite",
			spawnType = "hunter",
			difficultyCost = { 200, 250 },
			countClass = "terminator_nexbot_zambiereanimatorelite",
			maxCount = { 1, 2 },			
		},
		{
			hardRandomChance = nil,
			name = "zambie_grunt",
			prettyName = "Zombie Grunt",
			class = "terminator_nextbot_zambiegrunt",
			spawnType = "hunter",
			difficultyCost = { 4, 6 },
			countClass = "terminator_nextbot_zambiegrunt",
			maxCount = { 6, 8 },
		},
		{
			hardRandomChance = { 10, 30 },
			name = "zambie_grunt_elite",
			prettyName = "Zombie Grunt Elite",
			class = "terminator_nextbot_zambiegruntelite",
			spawnType = "hunter",
			difficultyCost = { 7, 10 },
			countClass = "terminator_nextbot_zambiegruntelite",
			maxCount = { 3, 4 },
		},
		{
			hardRandomChance = { 20, 40 },
			name = "zambie_beserker",
			prettyName = "Zombie Beserker",
			class = "terminator_nextbot_zambieberserk",
			spawnType = "hunter",
			difficultyCost = { 6, 8 },
			countClass = "terminator_nextbot_zambieberserk",
			maxCount = { 3, 4 },
		},
		{
			hardRandomChance = { 0.1, 1.5 },
			name = "zambie_tank_early",
			prettyName = "Zombie Tank Early",
			class = "terminator_nextbot_zambietank",
			spawnType = "hunter",
			difficultyCost = { 15, 20 },
			countClass = "terminator_nextbot_zambietank",
			maxCount = { 1 },
		},
		{
			hardRandomChance = nil,
			name = "zambie_tank",
			prettyName = "Zombie Tank",
			class = "terminator_nextbot_zambietank",
			spawnType = "hunter",
			difficultyCost = { 120, 150 },
			countClass = "terminator_nextbot_zambietank",
			maxCount = { 2, 3 },
		},
		{
			hardRandomChance = nil,
			name = "zambie_tank_elite",
			prettyName = "Zombie Tank",
			class = "terminator_nextbot_zambietankelite",
			spawnType = "hunter",
			difficultyCost = { 400, 500 },
			countClass = "terminator_nextbot_zambietankelite",
			maxCount = { 1, 2 },
		},
		{
			hardRandomChance = { 1, 3 },
			name = "zambie_mecha",
			prettyName = "Mecha Zombie",
			class = "terminator_nextbot_zambiemecha",
			spawnType = "hunter",
			difficultyCost = { 200, 225 },
			countClass = "terminator_nextbot_zambiemecha",
			maxCount = { 2, 4 },
		},
		{
			hardRandomChance = { 0.1, 1 },
			name = "zambie_mecha_elite",
			prettyName = "It's Joever",
			class = "terminator_nextbot_zambiemechaelite",
			spawnType = "hunter",
			difficultyCost = { 600, 800 },
			difficultyRequired = { 2000, 2500 },
			countClass = "terminator_nextbot_zambiemecha",
			maxCount = { 1, 2 },
		},
		{
			hardRandomChance = { 0.1, 0.5 },
			name = "zambie_cop",
			prettyName = "We're So Bidone",
			class = "terminator_nextbot_zambiecop",
			spawnType = "hunter",
			difficultyCost = { 1000, 1200 },
			difficultyRequired = { 4000, 5000 },
			countClass = "terminator_nextbot_zambiecop",
			maxCount = { 1 },
		},
	}

}

table.insert( GLEE_SPAWNSETS, reanimatorSpawnSet )