
local reanimatorSpawnSet = {
	name = "zambies_glee_reanim_collateral",
	prettyName = "Infinite Collateral Damage",
	description = "For masochists and sadists",
	difficultyPerMin = "default",
	waveInterval = "default",
	diffBumpWhenWaveKilled = "default",
	startingBudget = { 6, 8 },
	spawnCountPerDifficulty = "default",
	startingSpawnCount = 10,
	maxSpawnCount = 40,
	roundEndSound = "music/ravenholm_1.mp3",
	roundStartSound = "ambient/creatures/town_zombie_call1.wav",
	chanceToBeVotable = 10,
	spawns = {
		{
			hardRandomChance = { 20, 30 },
			name = "zambie_reanimator",
			prettyName = "Reanimator Zombie",
			class = "terminator_nextbot_zambiereanimator",
			spawnType = "hunter",
			difficultyCost = { 65, 70 },
			countClass = "terminator_nexbot_zambiereanimator",
			maxCount = { 4, 5 },
		},
		{
			hardRandomChance = { 25 },
			name = "zambie_reanimator_early",
			prettyName = "Reanimator Zombie Early",
			class = "terminator_nextbot_zambiereanimator",
			spawnType = "hunter",
			difficultyCost = { 6, 8 },
			difficultyStopAfter = { 60 },
			countClass = "terminator_nexbot_zambiereanimator",
			maxCount = { 1 },	
		},
		{
			hardRandomChance = { 40, 50 },
			name = "zambie_reanimator_elite",
			prettyName = "The Menace",
			class = "terminator_nextbot_zambiereanimatorelite",
			spawnType = "hunter",
			difficultyCost = { 300, 350 },
			countClass = "terminator_nexbot_zambiereanimatorelite",
			maxCount = { 1, 2 },			
		},
		{
			hardRandomChance = { 75 },
			name = "zambie_flame",
			prettyName = "Flaming Zombie",
			class = "terminator_nextbot_zambieflame",
			spawnType = "hunter",
			difficultyCost = { 3 },
			countClass = "terminator_nextbot_zambieflame*",
			maxCount = { 9, 11 },			
		},
		{
			hardRandomChance = { 25, 30 },
			name = "zambie_flame_fast",
			prettyName = "Flaming Zombie Fast",
			class = "terminator_nextbot_zambieflamefast",
			spawnType = "hunter",
			difficultyCost = { 5, 8 },
			countClass = "terminator_nextbot_zambieflame*",
			maxCount = 4,			
		},
		{
			hardRandomChance = { 75 },
			name = "zambie_acid",
			prettyName = "Acid Zombie",
			class = "terminator_nextbot_zambieacid",
			spawnType = "hunter",
			difficultyCost = { 3 },
			countClass = "terminator_nextbot_zambieacid*",
			maxCount = { 9, 11 },			
		},
		{
			hardRandomChance = { 25, 30 },
			name = "zambie_acid_fast",
			prettyName = "Acid Zombie Fast",
			class = "terminator_nextbot_zambieacidfast",
			spawnType = "hunter",
			difficultyCost = { 5, 8 },
			countClass = "terminator_nextbot_zambieacid*",
			maxCount = 4,			
		},
		{
			hardRandomChance = { 50, 60 },
			name = "zambie_energy",
			prettyName = "Energy Zombie",
			class = "terminator_nextbot_zambieenergy",
			spawnType = "hunter",
			difficultyCost = { 3, 4 },
			countClass = "terminator_nextbot_zambieenergy*",
			maxCount = { 6, 8 },			
		},
		{
			hardRandomChance = { 20, 25 },
			name = "zambie_energy_fast",
			prettyName = "Energy Zombie Fast",
			class = "terminator_nextbot_zambieenergyfast",
			spawnType = "hunter",
			difficultyCost = { 8, 10 },
			countClass = "terminator_nextbot_zambieenergy*",
			maxCount = 3,			
		},
		{
			hardRandomChance = { 10, 15 },
			name = "zambie_glass_elite",
			prettyName = "Glass Zombie Elite",
			class = "terminator_nextbot_zambieglasselite",
			spawnType = "hunter",
			difficultyCost = { 25, 35 },
			countClass = "terminator_nextbot_zambieglasselite",
			maxCount = { 3, 5 },			
		},
		{
			hardRandomChance = { 3 },
			name = "zambie_glass_titan",
			prettyName = "Glass Zombie Titan",
			class = "terminator_nextbot_zambieglasstitan",
			spawnType = "hunter",
			difficultyCost = { 250, 300 },
			difficultyRequired = { 500, 600 },
			countClass = "terminator_nextbot_zambieglasstitan",
			maxCount = { 1, 2 },			
		},
		{
			hardRandomChance = { 60 },
			name = "zambie_mech",
			prettyName = "Mecha Zombie",
			class = "terminator_nextbot_zambiemecha",
			spawnType = "hunter",
			difficultyCost = { 175, 250 },
			countClass = "terminator_nextbot_zambiemecha",
			maxCount = { 2, 3 },
		},
		{
			hardRandomChance = { 0.1, 1.5 },
			name = "zambie_mech_elite",
			prettyName = "Mecha Zombie Elite",
			class = "terminator_nextbot_zambiemechaelite",
			spawnType = "hunter",
			difficultyCost = { 300, 375 },
			difficultyRequired = { 1500 },
			countClass = "terminator_nextbot_zambiemecha*",
			maxCount = { 1 },
		},
	}
}

table.insert( GLEE_SPAWNSETS, reanimatorSpawnSet )