-- credit to https://steamcommunity.com/id/TakeTheBeansIDontCare/

local zambieSpawnSet = {
    name = "zambies_glee_harder", -- unique name
    prettyName = "Specially Infected Hell",
    description = "Zombies, everywhere!",
    difficultyPerMin = { 250 / 10, 500 / 10 }, -- difficulty per minute
    waveInterval = "default", -- time between spawn waves
    diffBumpWhenWaveKilled = "default", -- when there's <= 1 hunter left, the difficulty is permanently bumped by this amount
    startingBudget = "default", -- so budget isnt 0
    spawnCountPerDifficulty = { 2 }, -- go up to 20 fast pls
    startingSpawnCount = "default",
    maxSpawnCount = 25,
    maxSpawnDist = "default",
    chanceToBeVotable = 40,
    roundEndSound = "music/ravenholm_1.mp3",
    roundStartSound = "ambient/creatures/town_zombie_call1.wav",
    spawns = {
        {
            hardRandomChance = nil,
            name = "zambie_tank",
            prettyName = "A Tank Zombie",
            class = "terminator_nextbot_zambietank",
            spawnType = "hunter",
            difficultyCost = { 5, 50 },
            countClass = "terminator_nextbot_zambietank",
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_normal",
            prettyName = "A Zombie",
            class = "terminator_nextbot_zambie",
            spawnType = "hunter",
            difficultyCost = { 5 },
            countClass = "terminator_nextbot_zambie",
            maxCount = { 8 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_fast",
            prettyName = "A Fast Zombie",
            class = "terminator_nextbot_zambiefast",
            spawnType = "hunter",
            difficultyCost = { 5 },
            countClass = "terminator_nextbot_zambiefast",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_flaming",
            prettyName = "A Flaming Zombie",
            class = "terminator_nextbot_zambieflame",
            spawnType = "hunter",
            difficultyCost = { 20, 40 },
            countClass = "terminator_nextbot_zambieflame",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_flamingfast",
            prettyName = "A Fast Flaming Zombie",
            class = "terminator_nextbot_zambieflamefast",
            spawnType = "hunter",
            difficultyCost = { 25, 45 },
            countClass = "terminator_nextbot_zambieflamefast",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_acid",
            prettyName = "An Acid Zombie",
            class = "terminator_nextbot_zambieacid",
            spawnType = "hunter",
            difficultyCost = { 30, 60 },
            countClass = "terminator_nextbot_zambieacid",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_acid",
            prettyName = "An Fast Acid Zombie",
            class = "terminator_nextbot_zambieacidfast",
            spawnType = "hunter",
            difficultyCost = { 34, 66 },
            countClass = "terminator_nextbot_zambieacidfast",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_wraith",
            prettyName = "A Wraith",
            class = "terminator_nextbot_zambiewraith",
            spawnType = "hunter",
            difficultyCost = { 30, 60 },
            countClass = "terminator_nextbot_zambiewraith",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_fast_elite",
            prettyName = "An Elite Fast Zombie",
            class = "terminator_nextbot_zambiefastgrunt",
            spawnType = "hunter",
            difficultyCost = { 40, 80 },
            countClass = "terminator_nextbot_zambiefastgrunt",
            maxCount = { 3 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_wraith_elite",
            prettyName = "An Elite Wraith",
            class = "terminator_nextbot_zambiewraithelite",
            spawnType = "hunter",
            difficultyCost = { 60, 80 },
            countClass = "terminator_nextbot_zambiewraithelite",
            maxCount = { 3 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_grunt",
            prettyName = "A Zombie Grunt",
            class = "terminator_nextbot_zambiegrunt",
            spawnType = "hunter",
            difficultyCost = { 60, 70 },
            countClass = "terminator_nextbot_zambiegrunt",
            maxCount = { 6 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_grunt_elite",
            prettyName = "An Elite Zombie Grunt",
            class = "terminator_nextbot_zambiegruntelite",
            spawnType = "hunter",
            difficultyCost = { 100, 120 },
            countClass = "terminator_nextbot_zambiegruntelite",
            maxCount = { 3 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_tankelite",
            prettyName = "A Elite Tank Zombie",
            class = "terminator_nextbot_zambietankelite",
            spawnType = "hunter",
            difficultyCost = { 110, 135 },
            countClass = "terminator_nextbot_zambietankelite",
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_berserk",
            prettyName = "A Berserker Zombie",
            class = "terminator_nextbot_zambieberserk",
            spawnType = "hunter",
            difficultyCost = { 80, 90 },
            countClass = "terminator_nextbot_zambieberserk",
            maxCount = { 3 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_necromancerelite",
            prettyName = "A Elite Necromancer Zombie",
            class = "terminator_nextbot_zambienecroelite",
            spawnType = "hunter",
            difficultyCost = { 145, 165 },
            countClass = "terminator_nextbot_zambienecroelite",
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_necromancer",
            prettyName = "A Necromancer Zombie",
            class = "terminator_nextbot_zambienecro",
            spawnType = "hunter",
            difficultyCost = { 100, 120 },
            countClass = "terminator_nextbot_zambienecro",
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_godcrab",
            prettyName = "A Demigod Crab",
            class = "terminator_nextbot_zambiebigheadcrab",
            spawnType = "hunter",
            difficultyCost = { 150, 175 },
            countClass = "terminator_nextbot_zambiebigheadcrab",
            maxCount = { 8 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_godcrab",
            prettyName = "The God Crab",
            class = "terminator_nextbot_zambiebiggerheadcrab",
            spawnType = "hunter",
            difficultyCost = { 400, 600 },
            countClass = "terminator_nextbot_zambiebiggerheadcrab",
            maxCount = { 4 },
            postSpawnedFuncs = { screamAfterSpawning },
        },
    }
}

table.insert( GLEE_SPAWNSETS, zambieSpawnSet )
