
local genericZambieCounter = "terminator_nextbot_zambie*"

local zambieSpawnSet = {
    name = "zambies_glee_thehorde", -- unique name
    prettyName = "The Horde",
    description = "The horde is coming! The horde is coming!",
    difficultyPerMin = "default", -- difficulty per minute
    waveInterval = "default*0.25", -- time between spawn waves
    diffBumpWhenWaveKilled = "default", -- when there's <= 1 hunter left, the difficulty is permanently bumped by this amount
    startingBudget = 20, -- so budget isnt 0
    spawnCountPerDifficulty = { 1 }, -- go up fast pls
    startingSpawnCount = 40,
    maxSpawnCount = 50,
    roundEndSound = "music/ravenholm_1.mp3",
    roundStartSound = "ambient/creatures/town_zombie_call1.wav",
    chanceToBeVotable = 15,
    spawns = {
        {
            name = "zambie_slow",
            prettyName = "A Slow Zombie",
            class = "terminator_nextbot_zambie_slow",
            spawnType = "hunter",
            difficultyCost = 0.1,
            difficultyStopAfter = { 30, 40 },
            countClass = genericZambieCounter,
            minCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 5, 25 },
            name = "zambie_normal_RARE",
            prettyName = "A Zombie",
            class = "terminator_nextbot_zambie",
            spawnType = "hunter",
            difficultyCost = { 2, 4 },
            difficultyStopAfter = { 30, 40 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            name = "zambie_normal",
            prettyName = "A Zombie",
            class = "terminator_nextbot_zambie",
            spawnType = "hunter",
            difficultyCost = 0.1,
            difficultyNeeded = { 25, 35 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 1, 3 },
            name = "zambie_flaming_RARE", -- spawns early with a max count
            prettyName = "A Flaming Zombie",
            class = "terminator_nextbot_zambieflame",
            spawnType = "hunter",
            difficultyCost = { 1, 4 },
            difficultyNeeded = { 50, 100 },
            countClass = "terminator_nextbot_zambieflame*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 1, 3 },
            name = "zambie_fastflaming_RARE", -- spawns later but no max count
            prettyName = "A Fast Flaming Zombie",
            class = "terminator_nextbot_zambieflamefast",
            spawnType = "hunter",
            difficultyCost = { 2, 6 },
            difficultyNeeded = { 100, 150 },
            countClass = "terminator_nextbot_zambieflame*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_acid_RARE", -- spawns early with a max count
            prettyName = "An Acid Zombie",
            class = "terminator_nextbot_zambieacid",
            spawnType = "hunter",
            difficultyCost = { 4, 8 },
            countClass = "terminator_nextbot_zambieacid*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_acid_RARE", -- spawns later but no max count
            prettyName = "A Fast Acid Zombie",
            class = "terminator_nextbot_zambieacidfast",
            spawnType = "hunter",
            difficultyCost = { 8, 10 },
            difficultyNeeded = { 100, 150 },
            countClass = "terminator_nextbot_zambieacid*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 2.5, 5 },
            name = "zambie_grunt_RARE",
            prettyName = "A Zombie Grunt",
            class = "terminator_nextbot_zambiegrunt",
            spawnType = "hunter",
            difficultyCost = { 25, 50 },
            difficultyNeeded = { 25, 100 },
            countClass = "terminator_nextbot_zambiegrunt",
            maxCount = 1,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 5, 15 },
            name = "zambie_grunt_COMMON",
            prettyName = "A Zombie Grunt",
            class = "terminator_nextbot_zambiegrunt",
            spawnType = "hunter",
            difficultyCost = { 35, 65 },
            difficultyNeeded = { 200, 300 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 10, 25 },
            name = "zambie_fast",
            prettyName = "A Fast Zombie",
            class = "terminator_nextbot_zambiefast",
            spawnType = "hunter",
            difficultyCost = { 8, 12 },
            difficultyStopAfter = { 125, 250 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_torso",
            prettyName = "A Zombie Torso",
            class = "terminator_nextbot_zambietorso",
            spawnType = "hunter",
            difficultyCost = { 1 },
            countClass = "terminator_nextbot_zambietorso",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_fast_torso",
            prettyName = "A Fast Zombie Torso",
            class = "terminator_nextbot_zambietorsofast",
            spawnType = "hunter",
            difficultyCost = { 4 },
            countClass = "terminator_nextbot_zambietorsofast",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_wraith_torso",
            prettyName = "A Wraith Torso",
            class = "terminator_nextbot_zambietorsowraith",
            spawnType = "hunter",
            difficultyCost = { 10 },
            difficultyNeeded = { 15, 50 },
            countClass = "terminator_nextbot_zambietorsowraith",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_wraith_rare",
            prettyName = "A Wraith",
            class = "terminator_nextbot_zambiewraith",
            spawnType = "hunter",
            difficultyCost = { 10, 20 },
            difficultyNeeded = { 10, 75 },
            countClass = "terminator_nextbot_zambiewraith",
            maxCount = { 2, 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 1, 5 },
            name = "zambie_berserk",
            prettyName = "A Berserker Zombie",
            class = "terminator_nextbot_zambieberserk",
            spawnType = "hunter",
            difficultyCost = { 100, 150 },
            difficultyNeeded = { 100, 150 },
            countClass = "terminator_nextbot_zambieberserk",
            maxCount = { 0, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_tank",
            prettyName = "A Tank Zombie",
            class = "terminator_nextbot_zambietank",
            spawnType = "hunter",
            difficultyCost = { 100, 150 },
            difficultyNeeded = { 100, 200 },
            countClass = "terminator_nextbot_zambietank",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_necromancer",
            prettyName = "A Necromancer Zombie",
            class = "terminator_nextbot_zambienecro",
            spawnType = "hunter",
            difficultyCost = { 150, 200 },
            difficultyNeeded = { 100, 200 },
            countClass = "terminator_nextbot_zambienecro",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
    }
}

table.insert( GLEE_SPAWNSETS, zambieSpawnSet )
