
local genericZambieCounter = "terminator_nextbot_zambie*"

local zambieSpawnSet = {
    name = "zambies_glee_theslowhorde", -- unique name
    prettyName = "The Slow Horde",
    description = "The horde is... slowly.. approaching?",
    difficultyPerMin = "default", -- difficulty per minute
    waveInterval = "default*0.25", -- time between spawn waves
    diffBumpWhenWaveKilled = "default", -- when there's <= 1 hunter left, the difficulty is permanently bumped by this amount
    startingBudget = 10, -- so budget isnt 0
    spawnCountPerDifficulty = { 1 }, -- go up fast pls
    startingSpawnCount = 20,
    maxSpawnCount = 30,
    roundEndSound = "music/hl1_song5.mp3",
    roundStartSound = "music/hl2_song19.mp3",
    chanceToBeVotable = 0.5,
    chanceToBeVotableIfHard = 35,
    easy = true,
    spawns = {
        {
            name = "zambie_slow",
            prettyName = "A Slow Zombie",
            class = "terminator_nextbot_zambie_slow",
            spawnType = "hunter",
            difficultyCost = 0.1,
            countClass = genericZambieCounter,
            minCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 5, 25 },
            name = "zambie_normal_RARE",
            prettyName = "A Zombie",
            class = "terminator_nextbot_zambie",
            spawnType = "hunter",
            difficultyCost = { 2, 4 },
            difficultyStopAfter = { 30, 40 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.5, 1.5 },
            name = "zambie_flaming_RARE", -- rare spawn with a max count
            prettyName = "A Flaming Zombie",
            class = "terminator_nextbot_zambieflame",
            spawnType = "hunter",
            difficultyCost = { 1, 4 },
            difficultyNeeded = { 50, 100 },
            countClass = "terminator_nextbot_zambieflame*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0.5, 1.5 }, -- rare spawn with a max count
            name = "zambie_fastflaming_RARE",
            prettyName = "A Fast Flaming Zombie",
            class = "terminator_nextbot_zambieflamefast",
            spawnType = "hunter",
            difficultyCost = { 2, 6 },
            difficultyNeeded = { 100, 150 },
            countClass = "terminator_nextbot_zambieflame*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 }, -- rare spawn with a max count
            name = "zambie_acid_RARE",
            prettyName = "An Acid Zombie",
            class = "terminator_nextbot_zambieacid",
            spawnType = "hunter",
            difficultyCost = { 4, 8 },
            countClass = "terminator_nextbot_zambieacid*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 }, -- rare spawn with a max count
            name = "zambie_acid_RARE",
            prettyName = "A Fast Acid Zombie",
            class = "terminator_nextbot_zambieacidfast",
            spawnType = "hunter",
            difficultyCost = { 8, 10 },
            difficultyNeeded = { 100, 150 },
            countClass = "terminator_nextbot_zambieacid*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 }, -- rare spawn with a max count
            name = "zambie_energy_RARE",
            prettyName = "An Energy Zombie",
            class = "terminator_nextbot_zambieenergy",
            spawnType = "hunter",
            difficultyCost = { 4, 8 },
            countClass = "terminator_nextbot_zambieenergy*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 }, -- rare spawn with a max count
            name = "zambie_energyfast_RARE",
            prettyName = "A Fast Energy Zombie",
            class = "terminator_nextbot_zambieenergyfast",
            spawnType = "hunter",
            difficultyCost = { 8, 12 },
            countClass = "terminator_nextbot_zambieenergy*",
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 1.25, 2.5 }, -- rare grunt
            name = "zambie_grunt_RARE",
            prettyName = "A Zombie Grunt",
            class = "terminator_nextbot_zambiegrunt",
            spawnType = "hunter",
            difficultyCost = { 25, 50 },
            difficultyNeeded = { 25, 100 },
            countClass = "terminator_nextbot_zambiegrunt",
            maxCount = 1,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 5, 12.5 }, -- generic fast zombies
            name = "zambie_fast",
            prettyName = "A Fast Zombie",
            class = "terminator_nextbot_zambiefast",
            spawnType = "hunter",
            difficultyCost = { 8, 12 },
            difficultyStopAfter = { 125, 250 },
            countClass = genericZambieCounter,
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_torso",
            prettyName = "A Zombie Torso",
            class = "terminator_nextbot_zambietorso",
            spawnType = "hunter",
            difficultyCost = { 1 },
            countClass = "terminator_nextbot_zambietorso",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_fast_torso",
            prettyName = "A Fast Zombie Torso",
            class = "terminator_nextbot_zambietorsofast",
            spawnType = "hunter",
            difficultyCost = { 4 },
            countClass = "terminator_nextbot_zambietorsofast",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_wraith_torso",
            prettyName = "A Wraith Torso",
            class = "terminator_nextbot_zambietorsowraith",
            spawnType = "hunter",
            difficultyCost = { 10 },
            difficultyNeeded = { 15, 50 },
            countClass = "terminator_nextbot_zambietorsowraith",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_wraith_rare",
            prettyName = "A Wraith",
            class = "terminator_nextbot_zambiewraith",
            spawnType = "hunter",
            difficultyCost = { 10, 20 },
            difficultyNeeded = { 10, 75 },
            countClass = "terminator_nextbot_zambiewraith",
            maxCount = { 2, 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_phantom_rare",
            prettyName = "A Phantom",
            class = "terminator_nextbot_zambiephantom",
            spawnType = "hunter",
            difficultyCost = { 40, 80 },
            difficultyNeeded = { 50, 100 },
            countClass = "terminator_nextbot_zambiephantom",
            maxCount = { 1, 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_tank",
            prettyName = "A Tank Zombie",
            class = "terminator_nextbot_zambietank",
            spawnType = "hunter",
            difficultyCost = { 200, 400 },
            difficultyNeeded = { 200, 500 },
            countClass = "terminator_nextbot_zambietank",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_necromancer",
            prettyName = "A Necromancer Zombie",
            class = "terminator_nextbot_zambienecro",
            spawnType = "hunter",
            difficultyCost = { 300, 400 },
            difficultyNeeded = { 300, 800 },
            countClass = "terminator_nextbot_zambienecro",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 1 },
            name = "zambie_reanimator",
            prettyName = "A Reanimator Zombie",
            class = "terminator_nextbot_zambiereanimator",
            spawnType = "hunter",
            difficultyCost = { 2000, 4000 },
            difficultyNeeded = { 2000, 8000 },
            countClass = "terminator_nextbot_zambiereanimator",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = { 0, 2 },
            name = "zambie_demigodcrab",
            prettyName = "The Demigod Crab",
            class = "terminator_nextbot_zambiebigheadcrab",
            spawnType = "hunter",
            difficultyCost = { 1500, 2000 },
            difficultyNeeded = { 50000, 100000 },
            countClass = "terminator_nextbot_zambiebigheadcrab",
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
    }
}

table.insert( GLEE_SPAWNSETS, zambieSpawnSet )
