local zambieSpawnSet = {
    name = "zambies_glee", -- unique name
    prettyName = "Zambie's Glee",
    description = "Bring out your dead!",
    difficultyPerMin = "default", -- difficulty per minute
    waveInterval = "default", -- time between spawn waves
    diffBumpWhenWaveKilled = "default", -- when there's <= 1 hunter left, the difficulty is permanently bumped by this amount
    startingBudget = "default", -- so budget isnt 0
    spawnCountPerDifficulty = "default", -- max of ten at 10 minutes
    startingSpawnCount = "default",
    maxSpawnCount = "default",
    maxSpawnDist = "default",
    spawns = {
        {
            hardRandomChance = nil,
            name = "zambie_slow",
            prettyName = "A Slow Zombie",
            class = "terminator_nextbot_zambie_slow",
            spawnType = "hunter",
            difficultyCost = { 5 },
            countClass = "terminator_nextbot_zambie_slow",
            minCount = { 2 },
            maxCount = { 5 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_torso",
            prettyName = "A Zombie Torso",
            class = "terminator_nextbot_zambietorso",
            spawnType = "hunter",
            difficultyCost = { 5 },
            countClass = "terminator_nextbot_zambietorso",
            minCount = { 1 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_fast_torso",
            prettyName = "A Fast Zombie Torso",
            class = "terminator_nextbot_zambietorsofast",
            spawnType = "hunter",
            difficultyCost = { 10 },
            countClass = "terminator_nextbot_zambietorsofast",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_wraith_torso",
            prettyName = "A Wraith Torso",
            class = "terminator_nextbot_zambietorsowraith",
            spawnType = "hunter",
            difficultyCost = { 30 },
            countClass = "terminator_nextbot_zambietorsowraith",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_normal",
            prettyName = "A Zombie",
            class = "terminator_nextbot_zambie",
            spawnType = "hunter",
            difficultyCost = { 25, 50 },
            countClass = "terminator_nextbot_zambie",
            minCount = { 0 },
            maxCount = { 10 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_flaming",
            prettyName = "A Flaming Zombie",
            class = "terminator_nextbot_zambieflame",
            spawnType = "hunter",
            difficultyCost = { 40, 80 },
            countClass = "terminator_nextbot_zambieflame",
            minCount = { 0 },
            maxCount = { 5 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_fast",
            prettyName = "A Fast Zombie",
            class = "terminator_nextbot_zambiefast",
            spawnType = "hunter",
            difficultyCost = { 30, 50 },
            countClass = "terminator_nextbot_zambiefast",
            minCount = { 0 },
            maxCount = { 5 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_fast_elite",
            prettyName = "An Elite Fast Zombie",
            class = "terminator_nextbot_zambiefastgrunt",
            spawnType = "hunter",
            difficultyCost = { 55, 100 },
            countClass = "terminator_nextbot_zambiefastgrunt",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_wraith",
            prettyName = "A Wraith",
            class = "terminator_nextbot_zambiewraith",
            spawnType = "hunter",
            difficultyCost = { 60, 100 },
            countClass = "terminator_nextbot_zambiewraith",
            minCount = { 0 },
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_wraith_elite",
            prettyName = "An Elite Wraith",
            class = "terminator_nextbot_zambiewraithelite",
            spawnType = "hunter",
            difficultyCost = { 100, 135 },
            countClass = "terminator_nextbot_zambiewraithelite",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_acid",
            prettyName = "An Acid Zombie",
            class = "terminator_nextbot_zambieacid",
            spawnType = "hunter",
            difficultyCost = { 55, 110 },
            countClass = "terminator_nextbot_zambieacid",
            minCount = { 0 },
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_grunt",
            prettyName = "A Zombie Grunt",
            class = "terminator_nextbot_zambiegrunt",
            spawnType = "hunter",
            difficultyCost = { 60, 120 },
            countClass = "terminator_nextbot_zambiegrunt",
            minCount = { 0 },
            maxCount = { 4 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_grunt_elite",
            prettyName = "An Elite Zombie Grunt",
            class = "terminator_nextbot_zambiegruntelite",
            spawnType = "hunter",
            difficultyCost = { 145, 150 },
            countClass = "terminator_nextbot_zambiegruntelite",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_berserk",
            prettyName = "A Berserker Zombie",
            class = "terminator_nextbot_zambieberserk",
            spawnType = "hunter",
            difficultyCost = { 120, 150 },
            countClass = "terminator_nextbot_zambieberserk",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_tank",
            prettyName = "A Tank Zombie",
            class = "terminator_nextbot_zambietank",
            spawnType = "hunter",
            difficultyCost = { 50, 150 },
            countClass = "terminator_nextbot_zambietank",
            minCount = { 0 },
            maxCount = { 2 },
            postSpawnedFuncs = nil,
        },
        {
            hardRandomChance = nil,
            name = "zambie_necromancer",
            prettyName = "A Necromancer Zombie",
            class = "terminator_nextbot_zambienecro",
            spawnType = "hunter",
            difficultyCost = { 150, 200 },
            countClass = "terminator_nextbot_zambienecro",
            minCount = { 0 },
            maxCount = { 1 },
            postSpawnedFuncs = nil,
        },
    }
}

table.insert( GLEE_SPAWNSETS, zambieSpawnSet )
